### ISSUE TITLE
Todo for i2k workshop prep

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#302]
Tutorial repository: https://github.com/kephale/sciview-i2k

- [ ] Prepare datasets
- [x] Fix these bugs https://github.com/scenerygraphics/sciview/issues/301
- [ ] Finalize distance measurement tool https://github.com/scenerygraphics/sciview/issues/37
- [ ] Setup segmentation demo
- [ ] Setup cell tracking demo
- [ ] Setup point cloud demo
- [ ] Fix SNT integration
- [ ] Finalize extra mesh processing commands
- [ ] Complete syllabus https://github.com/scenerygraphics/sciview-docs/blob/master/workshops/i2k-2020.md
- [x] Kotlin conversion *and* elimination of `Vector3` and `Vector4` at the same time (to port default implementations as Kotlin extension functions
