### ISSUE TITLE
Fiji Future Testing

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#611]
- [ ] Multimesh demo has stl error
- [ ] RGB values of slice in image plane demo look off
- [ ] Volume render demo freezes

**TODO: Add more after resolving volume rendering**
